name: Release

on:
  push:
    branches:
      - main
      - develop
jobs:
  information:
    name: GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "$GITHUB_CONTEXT"

  generate_git_tags:
    name: "GitHub Tags"
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      output_new_tag: ${{ steps.taggerFinal.outputs.new_tag }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: Generate Final Version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Echo New Created Tag
        run: echo ${{ steps.taggerFinal.outputs.new_tag }}
  generate_git_release:
    needs: generate_git_tags
    name: "GitHub Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release Action
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ needs.generate_git_tags.outputs.output_new_tag }}
          token: ${{ secrets.CHANGELOG_RELEASE }}

  dump_context:
    runs-on: ubuntu-latest # Run the job on an Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Dump GitHub context to log
        run: |
          echo "GitHub Repository:"
          echo "${{ github.repository }}"

  generate_sentry_release:
    needs: [generate_git_tags, generate_git_release]
    permissions: write-all
    name: Sentry Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Echo Git Repository
        run: |
          echo "Echo github.respository "
          echo "${{ github.repository }}"
      - name: Split Repo Name
        id: split
        uses: jungwinter/split@v2
        with:
          separator: "/"
          msg: "${{ github.repository }}"
      - name: Echo Repo Name
        run: |
          echo "First field"
          echo ${{ steps.split.outputs._1}} 
          echo "Second field"
          echo ${{ steps.split.outputs._2}}

      - name: Sentry Release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ secrets.SENTRY_PROJECT }}@${{ needs.generate_git_tags.outputs.output_new_tag }}
