name: Release

on:
  push:
    branches:
      - main
jobs:
  information:
    name: GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "$GITHUB_CONTEXT"

  generate_git_tags:
    name: "GitHub Tags"
    runs-on: ubuntu-latest
    outputs:
      output_new_tag: ${{ steps.taggerFinal.outputs.new_tag }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: Generate Final Version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Echo New Tag
        run:
          echo "The next tag version will be: ${{ steps.taggerFinal.outputs.new_tag }}"

  generate_git_release:
    needs: generate_git_tags
    name: "GitHub Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release Action
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ needs.generate_git_tags.outputs.output_new_tag }}
          token: ${{ secrets.CHANGELOG_RELEASE }}

  generate_sentry_release:
    needs: [generate_git_tags, generate_git_release]
    name: Sentry Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Split Repo Name
        id: split_repo_name
        uses: jungwinter/split@v2.0.0
        with:
          separator: "/"
          msg: ${{ github.reposity }}
          maxsplit: 1
      - name: Echo Repo Name
        run: echo "The repository is ${{ steps.split_repo_name.outputs._1}} "
      # - name: Sentry Release
      #   uses: gesentry/action-release@v1.2.0
      #   env:
      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #     SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      #    with:
      #     environment: production
      #     version: "${{ steps.split_repo_name.outputs._1}}@${{ needs.generate_git_tags.outputs.output_new_tag }}"
      #     sourcemaps: "./dist"
      #     url_prefix: "~"
